name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.CI_TOKEN }}

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      # - run: npx playwright@latest install --with-deps
      - uses: nrwl/nx-set-shas@v4

      - name: check formatting
        run: npx nx-cloud record -- nx format:check

      # When you enable task distribution, run the e2e-ci task instead of e2e
      - run: npx nx affected -t lint test build e2e-ci

      - run: npx nx-cloud fix-ci
        if: always()
